import { LegalPageLayout, LegalSection } from './LegalPageLayout';

const CONTACT_EMAIL = 'autocardssupport@gmail.com';

export function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="August 9, 2026">
      <LegalSection heading="Acceptance of Terms">
        <p>
          By creating an account or using Auto Cards, you agree to these terms. If you don't
          agree, please don't use the service.
        </p>
      </LegalSection>

      <LegalSection heading="Description of Service">
        <p>
          Auto Cards turns documents you upload into flashcards, and provides tools to study,
          track, and sync them across devices.
        </p>
      </LegalSection>

      <LegalSection heading="Accounts">
        <p>
          You're responsible for the accuracy of the information you provide and for keeping your
          login credentials secure. You're responsible for activity that happens under your
          account.
        </p>
      </LegalSection>

      <LegalSection heading="Subscriptions & Billing">
        <p>
          Auto Cards offers a free plan, a Pro plan billed at $4/month, and a one-time Lifetime
          purchase at $39. Subscription payments are processed by Stripe.
        </p>
        <p>
          You can cancel a Pro subscription at any time; your plan stays active until the end of
          the current billing period. Fees already paid are non-refundable except where required
          by law.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable Use">
        <p>
          Don't upload content you don't have the right to use, and don't use Auto Cards to
          generate or distribute illegal, infringing, or abusive material. We may suspend accounts
          that abuse the generation system (for example, automated or excessive requests intended
          to bypass plan limits).
        </p>
      </LegalSection>

      <LegalSection heading="Your Content & AI-Generated Cards">
        <p>
          You retain ownership of the documents you upload. By uploading a document, you grant us
          a license to process it in order to generate flashcards for your account.
        </p>
        <p>
          Flashcards are generated by an AI model and may contain errors, omissions, or
          inaccuracies. Auto Cards is a study aid, not a substitute for verifying facts against
          your source material.
        </p>
      </LegalSection>

      <LegalSection heading="Intellectual Property">
        <p>
          The Auto Cards name, branding, and underlying software belong to us. These terms don't
          grant you any rights to them beyond what's needed to use the service.
        </p>
      </LegalSection>

      <LegalSection heading="Termination">
        <p>
          You can delete your account at any time. We may suspend or terminate accounts that
          violate these terms.
        </p>
      </LegalSection>

      <LegalSection heading="Disclaimer of Warranties">
        <p>
          Auto Cards is provided "as is," without warranties of any kind, express or implied.
        </p>
      </LegalSection>

      <LegalSection heading="Limitation of Liability">
        <p>
          To the fullest extent permitted by law, Auto Cards is not liable for indirect,
          incidental, or consequential damages arising from your use of the service.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to These Terms">
        <p>
          We may update these terms from time to time. Continued use of Auto Cards after a change
          means you accept the updated terms.
        </p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>
          Questions about these terms? Email us at{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="underline hover:text-slate-900 dark:hover:text-white">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
